...

diff --git a/.github/workflows/validate_branch_name.yml b/.github/workflows/validate_branch_name.yml
--- a/.github/workflows/validate_branch_name.yml
+++ b/.github/workflows/validate_branch_name.yml
@@ -10,10 +10,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check branch name
-        run: |
-          branch_name=$(echo "${GITHUB_REF##*/}")
-          if [[ ! "$branch_name" =~ ^(feature|fix|hotfix)\/.+ ]]; then
-            echo "Error: The branch name must start with 'feature/', 'fix/', or 'hotfix/'."
-            exit 1
-          fi
+    - name: Validar formato de la rama
+      run: |
+        # obtenemos el nombre completo de la rama (p.ej. feature/fix-backport)
+        branch_name=${GITHUB_REF#refs/heads/}
+        echo "Branch name is '$branch_name'"
+    
+        if [[ ! "$branch_name" =~ ^(feature|fix|hotfix)/.+ ]]; then
+          echo "Error: El nombre de la rama debe empezar con 'feature/', 'fix/' o 'hotfix/'."
+          exit 1
+        fi
+    
+        echo "✅ El nombre de la rama cumple el patrón."
